version: "3"
services:
  app:
    build: ./app
    volumes:
      - ./app/flaskapp:/app
      - socket:/tmp
    command: uwsgi --ini /app/app.ini
    environment:
      FLASK_ENV: "development"
      FLASK_APP: ./app.py

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp

volumes:
  socket:
